# Generated by Django 2.2.1 on 2019-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0006_garbage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Waiting for Acknowledgement', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
